### ISSUE TITLE
Use with the Electrum AppImage

### ISSUE THREAD

**Issue by tiero** [bwt-dev/bwt-electrum-plugin#2]
Unfortunately Tails has not the recent Electrum version and since I cannot use pip I cannot either install from source.

The only option is to use AppImage, but AFAIK this plugin cannot work with it. There is any workaround to this?

(I cannot use the old Electrum, because my watch-only wallet has been created with a recent electrum version and is not compatible)

**Comment by shesek** [comment]
I'm afraid that I'm not aware of a workaround for using the AppImage. It's not just that bwt can't work with it, it cannot be used with external electrum plugins at all.

But I'll investigate some more and report back, I might have an idea that could work...

**Comment by shesek** [comment]
Okay, so its actually pretty simple!

```bash
# Extract AppImage (to a subdirectory named 'squashfs-root')
$ ./electrum-x.y.z-x86_64.AppImage --appimage-extract

# Copy the bwt plugin directory
$ cp -r /path/to/bwt squashfs-root/usr/lib/python3.7/site-packages/electrum/plugins

# Start Electrum, setup bwt, then run again without --offline
./squashfs-root/AppRun --offline
```

(The `--offline` thing is unrelated to the AppImage, just a general recommendation to avoid acceidntly connecting to public servers.)

**Comment by shesek** [comment]
I added [some instructions](https://github.com/bwt-dev/bwt-electrum-plugin#with-the-electrum-appimage) and a [small helper script](https://github.com/bwt-dev/bwt-electrum-plugin/blob/master/src/run-appimage.sh) to ease the setup.

Thanks for getting me to look into this again!

**Comment by shesek** [comment]
Reopening until you confirm this works for you.

**Comment by shesek** [comment]
It worked on various environments that I tried this on, closing.
